In [19]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [20]:
# Veri ekleme
dataset = pd.read_csv("veri.csv")

In [21]:
# Bağımsız ve bağımlı değişkenleri ayırma
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values 

In [22]:
# Kayıp veri doldurma (eğer varsa)
imputer = SimpleImputer(strategy="mean")
X[:, 1:3] = imputer.fit_transform(X[:, 1:3])

In [23]:
# CafeCategory sütunu 4. indekste
ct = ColumnTransformer(
    transformers=[
        ("encoder", OneHotEncoder(), [4])  # Sadece CafeCategory (4. sütun) dönüştürülüyor
    ],
    remainder="passthrough"  # Diğer sütunlar olduğu gibi bırakılır
)

# Dönüşüm
X = np.array(ct.fit_transform(X))
print(X)

[[0.0 1.0 0.0 ... 1.0 1.0 0]
 [1.0 0.0 0.0 ... 0.0 0.0 0]
 [0.0 1.0 0.0 ... 0.0 0.0 0]
 ...
 [0.0 0.0 1.0 ... 0.0 0.0 0]
 [0.0 1.0 0.0 ... 0.0 0.0 0]
 [0.0 0.0 1.0 ... 0.0 0.0 1]]


In [24]:
# İşlenmiş verileri birleştirmek için DataFrame oluşturma
veri = pd.DataFrame(np.hstack((X, y.reshape(-1, 1))))

In [26]:
# CSV dosyasına kaydetme
veri.to_csv("veriOnIslendi.csv", index=False,header=False)